### ISSUE TITLE
Criação de tabelas deve ser feita no activation_hook e versão da(s) tabela(s)

### ISSUE THREAD

**Issue by nicholasio** [leobaiano/post-useful#4]
A tabela post_useful está sendo criada na action init. 

``` php
add_action( 'init', array( $this, 'create_table' ) );
```

Porém ela deveria ser criada no activation_hook, conforme https://codex.wordpress.org/Creating_Tables_with_Plugins.

Isso economiza uma consulta toda vez que o plugin for carregado.

Além disso é sempre bom salvar a versão do "banco" do plugin para caso necessite fazer atualizações no banco no futuro. Existe uma var

``` php
$post_useful_db_version = '1.0'; 
```

mas a mesma não está sendo salva no banco.

**Comment by leobaiano** [comment]
Opa, boa @nicholasio!
