### ISSUE TITLE
Traduzir links de votação

### ISSUE THREAD

**Issue by dbasilioesp** [leobaiano/post-useful#7]
Os links não estão sendo traduzidos, ao remover a imagem de fundo utilizando CSS para estilizar de acordo com o site sendo desenvolvido, a palavra que aparece é **Yes** e **No**.

Como já há tradução para essas duas palavras, não acho que seria um problema.

**Comment by leobaiano** [comment]
Muito obrigado pelo feedback, fiz a correção!
